"""empty message

Revision ID: 9c4a775233fe
Revises: 2dd99edeed80
Create Date: 2023-05-09 17:33:27.820343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4a775233fe'
down_revision = '2dd99edeed80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_pet_id_fkey', type_='foreignkey')
        batch_op.drop_column('pet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_pet_id_fkey', 'pet', ['pet_id'], ['id'])

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
